// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20210331182855_ManyToMany")]
    partial class ManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ArmHand", b =>
                {
                    b.Property<Guid>("ArmsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HandsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ArmsId", "HandsId");

                    b.HasIndex("HandsId");

                    b.ToTable("ArmHand");
                });

            modelBuilder.Entity("FingerHand", b =>
                {
                    b.Property<Guid>("FingersId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HandsId")
                        .HasColumnType("TEXT");

                    b.HasKey("FingersId", "HandsId");

                    b.HasIndex("HandsId");

                    b.ToTable("FingerHand");
                });

            modelBuilder.Entity("types.Arm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Arms");
                });

            modelBuilder.Entity("types.Finger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DigitName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fingers");
                });

            modelBuilder.Entity("types.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chirality")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("ArmHand", b =>
                {
                    b.HasOne("types.Arm", null)
                        .WithMany()
                        .HasForeignKey("ArmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("types.Hand", null)
                        .WithMany()
                        .HasForeignKey("HandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FingerHand", b =>
                {
                    b.HasOne("types.Finger", null)
                        .WithMany()
                        .HasForeignKey("FingersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("types.Hand", null)
                        .WithMany()
                        .HasForeignKey("HandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
